/* Regenerate data/index.js + data/dict.js from data/articles/*.json + data/dictionary.json
   Includes schema validation and injects a content-hash version into sw.js */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const root = path.join(__dirname, '..');
const errors = [];

/* ---------- 读取并校验文章 ---------- */
const artDir = path.join(root, 'data', 'articles');
const REQUIRED = ['id', 'title', 'source', 'topic', 'difficulty', 'year', 'wordCount', 'paragraphs'];
const articles = fs.readdirSync(artDir)
  .filter(f => f.endsWith('.json'))
  .sort()
  .map(f => {
    let a;
    try {
      a = JSON.parse(fs.readFileSync(path.join(artDir, f), 'utf8'));
    } catch (e) {
      errors.push(`${f}: JSON 解析失败 - ${e.message}`);
      return null;
    }
    REQUIRED.forEach(k => { if (a[k] === undefined || a[k] === null || a[k] === '') errors.push(`${f}: 缺少字段 ${k}`); });
    if (!Array.isArray(a.paragraphs) || !a.paragraphs.length) {
      errors.push(`${f}: paragraphs 为空或不是数组`);
    } else {
      a.paragraphs.forEach((p, i) => {
        if (!p || typeof p.en !== 'string' || !p.en.trim()) errors.push(`${f}: 第 ${i + 1} 段缺少英文`);
        if (!p || typeof p.zh !== 'string' || !p.zh.trim()) errors.push(`${f}: 第 ${i + 1} 段缺少中文译文`);
      });
    }
    if (a.id && a.id !== f.replace(/\.json$/, '')) errors.push(`${f}: id "${a.id}" 与文件名不一致`);
    return a;
  })
  .filter(Boolean);

const seenIds = new Set();
articles.forEach(a => {
  if (seenIds.has(a.id)) errors.push(`文章 id 重复: ${a.id}`);
  seenIds.add(a.id);
});

/* ---------- 读取并校验词典 ---------- */
const dict = JSON.parse(fs.readFileSync(path.join(root, 'data', 'dictionary.json'), 'utf8'));
if (!Array.isArray(dict.words)) errors.push('dictionary.json: 缺少 words 数组');
const seenWords = new Set();
(dict.words || []).forEach(e => {
  if (!e.word || typeof e.definition !== 'string' || !e.definition.trim()) errors.push(`词典条目异常: ${JSON.stringify(e).slice(0, 80)}`);
  const w = (e.word || '').toLowerCase();
  if (seenWords.has(w)) errors.push(`词典单词重复: ${w}`);
  seenWords.add(w);
});

if (errors.length) {
  console.error('数据校验失败：');
  errors.slice(0, 30).forEach(e => console.error('  - ' + e));
  if (errors.length > 30) console.error(`  ... 共 ${errors.length} 个错误`);
  process.exit(1);
}

/* ---------- 输出：索引（仅元信息）+ 词典 ---------- */
const index = articles.map(({ id, title, source, sourceZh, topic, difficulty, year, wordCount }) =>
  ({ id, title, source, sourceZh, topic, difficulty, year, wordCount }));

const indexOut = `// Auto-generated by tools/build-data.js. Do not edit by hand.\nwindow.KAOYAN_INDEX = ${JSON.stringify(index)};\n`;
const dictOut = `// Auto-generated by tools/build-data.js. Do not edit by hand.\nwindow.KAOYAN_DICT = ${JSON.stringify(dict.words)};\n`;

const outDir = path.join(root, 'data');
fs.writeFileSync(path.join(outDir, 'index.js'), indexOut, 'utf8');
fs.writeFileSync(path.join(outDir, 'dict.js'), dictOut, 'utf8');

/* ---------- 向 sw.js 注入内容哈希版本号 ---------- */
const hash = crypto.createHash('sha1').update(indexOut + dictOut).digest('hex').slice(0, 10);
const version = 'kaoyan-reader-' + hash;
const swPath = path.join(root, 'sw.js');
const sw = fs.readFileSync(swPath, 'utf8');
const CACHE_RE = /var CACHE = '[^']*';/;
if (!CACHE_RE.test(sw)) {
  console.error('sw.js 中未找到 CACHE 版本声明（var CACHE = \'...\';），无法注入版本号');
  process.exit(1);
}
const updated = sw.replace(CACHE_RE, `var CACHE = '${version}';`);
fs.writeFileSync(swPath, updated, 'utf8');

/* ---------- 体积报告 ---------- */
const kb = n => (n / 1024).toFixed(1) + ' KB';
console.log(`articles: ${articles.length}, dict words: ${dict.words.length}`);
console.log(`data/index.js: ${kb(Buffer.byteLength(indexOut))} | data/dict.js: ${kb(Buffer.byteLength(dictOut))}`);
console.log(`sw.js cache version: ${version}`);
