/* Download Latin woff2 subsets of the project fonts from Google Fonts into fonts/
   Run once (or when changing font weights): node tools/fetch-fonts.js */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const outDir = path.join(root, 'fonts');
const CSS_URL = 'https://fonts.googleapis.com/css2?family=Libre+Bodoni:ital,wght@0,400;0,500;0,600;0,700;1,400&family=Public+Sans:wght@400;500;600;700&display=swap';
/* Chrome UA makes the css2 API return woff2 sources */
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';

const SLUG = { 'Libre Bodoni': 'libre-bodoni', 'Public Sans': 'public-sans' };

async function main() {
  const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();
  /* split into @font-face blocks */
  const blocks = css.split('@font-face').slice(1);
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir);
  const faces = [];
  for (const block of blocks) {
    const get = re => { const m = block.match(re); return m ? m[1] : null; };
    const family = get(/font-family:\s*'([^']+)'/);
    const style = get(/font-style:\s*([a-z-]+);/);
    const weight = get(/font-weight:\s*([\d ]+);/);
    const range = get(/unicode-range:\s*([^;]+);/);
    const url = get(/url\((https:[^)]+\.woff2)\)/);
    if (!family || !url || !SLUG[family]) continue;
    /* keep only the latin subset */
    if (!range || range.indexOf('U+0000-00FF') === -1) continue;
    const file = `${SLUG[family]}${style === 'italic' ? '-italic' : ''}-${weight.trim()}.woff2`;
    const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
    fs.writeFileSync(path.join(outDir, file), buf);
    faces.push({ family, style, weight: weight.trim(), file });
    console.log(`downloaded ${file} (${(buf.length / 1024).toFixed(1)} KB)`);
  }
  /* emit css/fonts.css with @font-face declarations */
  const cssOut = ['/* Auto-generated by tools/fetch-fonts.js. Do not edit by hand. */']
    .concat(faces.map(f =>
      `@font-face {\n` +
      `  font-family: "${f.family}";\n` +
      `  font-style: ${f.style};\n` +
      `  font-weight: ${f.weight};\n` +
      `  font-display: swap;\n` +
      `  src: url("../fonts/${f.file}") format("woff2");\n` +
      `}`))
    .join('\n\n') + '\n';
  fs.writeFileSync(path.join(root, 'css', 'fonts.css'), cssOut, 'utf8');
  console.log(`fonts: ${faces.length} files -> fonts/, css/fonts.css generated`);
}

main().catch(e => { console.error(e); process.exit(1); });
